# Generated by Django 3.0 on 2022-02-03 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20220203_1706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='date_completed',
            new_name='datecompleted',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='date_created',
            new_name='datecreated',
        ),
    ]
