# Generated by Django 3.0 on 2022-02-04 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20220203_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='datecreated',
            field=models.DateField(auto_now_add=True),
        ),
    ]
