# Generated by Django 3.0 on 2022-02-04 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20220204_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='datecreated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
